# syntax=docker/dockerfile:1

# Canvas Student Data Export Tool - API only, no browser or Node.js required.
FROM python:3.12-slim AS runtime

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY export.py html_export.py naming.py ./

# Run as a regular user (uid 1000 usually matches the host user, which keeps
# bind-mounted output directories writable on Linux). Use `--user` to override.
RUN useradd --create-home --uid 1000 exporter \
    && mkdir -p /data /config \
    && chown exporter:exporter /data /config

USER exporter

# Container defaults: mount credentials at /config and output at /data.
# Credentials can also be supplied through CANVAS_* environment variables.
# HTML pages are generated by default; set CANVAS_HTML=0 to skip them.
ENV CANVAS_CONFIG=/config/credentials.yaml \
    CANVAS_HTML=1
VOLUME ["/data"]

ENTRYPOINT ["python", "export.py"]
CMD ["-o", "/data"]
