"""Convert downloaded Canvas files to Markdown.

This rewrites the project's original Windows ``.bat`` pandoc workflow in
Python and adds a fast path for HTML pages generated by ``html_export.py``.

The reference ``.bat`` behaviour (minus Windows-isms) is reproduced here:

- For each html/htm/docx/doc/pptx/txt/xlsx file it ran pandoc with a specific
  input format for HTML, a specific Markdown output format,
  ``--wrap=none --column=999 --extract-media=./attachments/<stem>``, and a Lua
  filter that unwraps Bootstrap/R Markdown container ``Div`` elements.
- Output went to ``<same dir>/<stem>.md`` and existing outputs were skipped.
- Afterwards a few cleanup regexes were applied and the output mtime was synced
  to the input mtime.
- Extracted ``.emf`` images were best-effort converted to ``.png`` with
  ImageMagick and the reference in the Markdown rewritten.

Pandoc is resolved lazily (``find_pandoc``) and is never required at import
time. ``.doc`` is intentionally not supported because pandoc cannot read the
legacy binary format.
"""

import os
import re
import shutil
import subprocess
import tempfile
import urllib.parse

from typing import Optional

from naming import makeValidFilename

# Embedded in every page written by html_export.py.
GENERATED_HTML_MARKER = 'name="generator" content="canvas-student-data-export"'

# Prepended to Markdown written from pages generated by this exporter, so
# downstream tooling (e.g. NotebookLM uploads) can recognise them.
GENERATED_MD_MARKER = "<!-- generated-by: canvas-student-data-export -->"

# Lowercase extensions pandoc can read here. .doc is deliberately excluded
# because pandoc has no reader for the legacy binary format.
PANDOC_EXTENSIONS = {
    ".html", ".htm", ".docx", ".odt", ".epub", ".rtf", ".txt", ".pptx",
    ".xlsx", ".tex", ".rst", ".org", ".csv",
}

# pandoc reader/writer options used by the original .bat file.
_PANDOC_INPUT_FORMAT = (
    "html-native_divs-native_spans+tex_math_dollars+tex_math_single_backslash"
)
_PANDOC_OUTPUT_FORMAT = (
    "markdown-bracketed_spans+backtick_code_blocks+tex_math_dollars"
    "+fenced_code_attributes+fenced_divs+footnotes-simple_tables"
    "-multiline_tables-grid_tables-table_captions+superscript+subscript"
)

_PANDOC_TIMEOUT = 600.0
_MAGICK_TIMEOUT = 120.0

# Lua filter matching the original clean.lua: return the children of container
# Divs so their contents are unwrapped instead of being dropped.
_CLEAN_LUA = """-- Unwrap container Divs emitted by Bootstrap / R Markdown HTML.
local unwrap_classes = {
  panel = true,
  ["panel-body"] = true,
  ["panel-group"] = true,
  ["panel-heading"] = true,
  ["container-fluid"] = true,
  ["main-container"] = true,
}

function Div(el)
  if el.classes then
    for _, cls in ipairs(el.classes) do
      if unwrap_classes[cls] then
        return el.content
      end
    end
  end
end
"""

_lua_filter_path = None


def _write_clean_lua():
    """Write clean.lua once into the temp dir; return its path or None."""
    global _lua_filter_path
    if _lua_filter_path is not None:
        return _lua_filter_path or None

    path = None
    try:
        # mkstemp creates a 0600 file with an unpredictable name, so a shared
        # /tmp cannot be used to redirect this write via a symlink.
        fd, path = tempfile.mkstemp(prefix="canvas-clean-", suffix=".lua")
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(_CLEAN_LUA)
        _lua_filter_path = path
    except OSError:
        _lua_filter_path = ""
    return _lua_filter_path or None


def find_pandoc() -> Optional[str]:
    """Return path to a pandoc executable, or None. Checks PANDOC env var, then PATH."""
    from_env = os.environ.get("PANDOC")
    if from_env:
        return from_env
    return shutil.which("pandoc")


def is_generated_html(path: str) -> bool:
    """True when the file is an HTML page written by html_export.py (marker present)."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            head = f.read(64 * 1024)
    except OSError:
        return False
    return GENERATED_HTML_MARKER in head


def attachment_dir_for(source_path: str) -> str:
    """<dir>/attachments/<stem> -- same layout as the .bat --extract-media."""
    directory = os.path.dirname(os.path.abspath(source_path))
    stem = os.path.splitext(os.path.basename(source_path))[0]
    stem = makeValidFilename(stem) if stem else "file"
    return os.path.join(directory, "attachments", stem)


def _md_path_for(source_path):
    return os.path.splitext(source_path)[0] + ".md"


def _cleanup_markdown(text):
    """Apply the .bat's post-conversion cleanup regexes."""
    text = re.sub(r"-{4,}", "---", text)
    text = re.sub(r"={4,}", "===", text)
    text = re.sub(r"\\([><\^_\$])", r"\1", text)
    return text


def _sync_mtime(source_path, output_path):
    """Sync the output mtime to the input mtime (best effort)."""
    try:
        mtime = os.path.getmtime(source_path)
        os.utime(output_path, (mtime, mtime))
    except OSError:
        pass


def _convert_emf(emf_path):
    """Best-effort EMF -> PNG with ImageMagick; return png path or None."""
    png_path = os.path.splitext(emf_path)[0] + ".png"
    for tool in ("magick", "convert"):
        exe = shutil.which(tool)
        if not exe:
            continue
        try:
            subprocess.run(
                [exe, emf_path, png_path],
                capture_output=True,
                text=True,
                timeout=_MAGICK_TIMEOUT,
            )
        except Exception:
            continue
        if os.path.isfile(png_path) and os.path.getsize(png_path) > 0:
            return png_path
    return None


def _rewrite_emf_refs(text, attachment_dir):
    """Convert extracted .emf media to .png and rewrite references (best effort)."""
    if not os.path.isdir(attachment_dir):
        return text

    emf_paths = []
    for root, _dirs, files in os.walk(attachment_dir):
        for name in files:
            if name.lower().endswith(".emf"):
                emf_paths.append(os.path.join(root, name))

    for emf_path in emf_paths:
        png_path = _convert_emf(emf_path)
        if not png_path:
            continue
        emf_name = os.path.basename(emf_path)
        png_name = os.path.basename(png_path)
        text = text.replace(emf_name, png_name)
        text = text.replace(
            urllib.parse.quote(emf_name), urllib.parse.quote(png_name)
        )
    return text


def _run_pandoc(source_path, output_path, pandoc):
    """Run pandoc for one file. True on success (partial .md removed on failure)."""
    attachment_dir = attachment_dir_for(source_path)
    ext = os.path.splitext(source_path)[1].lower()

    cmd = [pandoc, source_path]
    if ext in (".html", ".htm"):
        cmd += ["-f", _PANDOC_INPUT_FORMAT]
    cmd += [
        "-t", _PANDOC_OUTPUT_FORMAT,
        "--wrap=none",
        "--column=999",
        "--extract-media=" + attachment_dir,
    ]
    lua_filter = _write_clean_lua()
    if lua_filter:
        cmd += ["--lua-filter=" + lua_filter]
    cmd += ["-o", output_path]

    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=_PANDOC_TIMEOUT
        )
    except Exception:
        proc = None

    if proc is None or proc.returncode != 0:
        if os.path.exists(output_path):
            try:
                os.remove(output_path)
            except OSError:
                pass
        return False
    return True


def _pandoc_markdown(source_path, output_path, pandoc):
    """Run pandoc, clean the result, and return the Markdown text (or None)."""
    if not _run_pandoc(source_path, output_path, pandoc):
        return None
    try:
        with open(output_path, "r", encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return None

    text = _cleanup_markdown(text)
    text = _rewrite_emf_refs(text, attachment_dir_for(source_path))

    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(text)
    except OSError:
        return None
    return text


def _html_to_markdown(inner_html):
    """Convert an HTML fragment with markdownify, or None when unavailable."""
    try:
        from markdownify import markdownify
    except Exception:
        return None
    try:
        return markdownify(
            inner_html,
            heading_style="ATX",
            bullets="-",
            strip=["script", "style"],
        )
    except Exception:
        return None


def markdownify_available() -> bool:
    """True when the markdownify package can be imported."""
    try:
        import importlib.util
        return importlib.util.find_spec("markdownify") is not None
    except Exception:
        return False


def _main_inner_html(soup):
    """Return <main> inner HTML, falling back to <body> then the whole document."""
    main = soup.find("main")
    if main is not None:
        inner = main.decode_contents()
        if inner.strip():
            return inner
    body = soup.body
    if body is not None:
        return body.decode_contents()
    return soup.decode_contents()


def generated_html_to_markdown(html_path: str, md_path: Optional[str] = None) -> Optional[str]:
    """Convert a page we generated (no pandoc) to Markdown.

    Parses with BeautifulSoup, takes <main> inner HTML (falling back to
    <body>), and converts with `markdownify` when that package is importable
    (imported lazily). Otherwise it falls back to pandoc if available, else
    returns None. The written file starts with GENERATED_MD_MARKER + newline.
    Returns the md path written or None. Never overwrites an existing md.
    """
    try:
        if md_path is None:
            md_path = _md_path_for(html_path)
        if os.path.exists(md_path):
            return None

        try:
            with open(html_path, "r", encoding="utf-8", errors="replace") as f:
                html_text = f.read()
        except OSError:
            return None

        markdown = None
        try:
            from bs4 import BeautifulSoup
        except Exception:
            BeautifulSoup = None

        if BeautifulSoup is not None:
            try:
                soup = BeautifulSoup(html_text, "html.parser")
                markdown = _html_to_markdown(_main_inner_html(soup))
            except Exception:
                markdown = None

        if markdown is not None:
            text = GENERATED_MD_MARKER + "\n" + markdown
            try:
                with open(md_path, "w", encoding="utf-8") as f:
                    f.write(text)
            except OSError:
                return None
            _sync_mtime(html_path, md_path)
            return md_path

        # markdownify (or BeautifulSoup) is unavailable: fall back to pandoc.
        tool = find_pandoc()
        if not tool:
            return None
        body = _pandoc_markdown(html_path, md_path, tool)
        if body is None:
            return None
        try:
            with open(md_path, "w", encoding="utf-8") as f:
                f.write(GENERATED_MD_MARKER + "\n" + body)
        except OSError:
            return None
        _sync_mtime(html_path, md_path)
        return md_path
    except Exception as e:
        print(f"    ERROR: converting generated HTML {html_path}: {e}")
        return None


def convert_file(source_path: str, pandoc: Optional[str] = None, force: bool = False) -> Optional[str]:
    """Convert one file to `<stem>.md` next to it.

    Uses generated_html_to_markdown for generated HTML, pandoc for everything
    else. Returns md path or None (unsupported / tool missing / failed).
    Never raises.
    """
    try:
        source_path = os.path.abspath(source_path)
        if not os.path.isfile(source_path):
            print(f"    Skipping: not a file: {source_path}")
            return None

        ext = os.path.splitext(source_path)[1].lower()
        output_path = _md_path_for(source_path)

        if is_generated_html(source_path):
            if os.path.exists(output_path) and not force:
                print(f"    Skipping: {output_path} already exists")
                return None
            if force and os.path.exists(output_path):
                try:
                    os.remove(output_path)
                except OSError:
                    pass
            result = generated_html_to_markdown(source_path, output_path)
            if result:
                print(f"    ✓ Converted (generated HTML): {source_path} -> {output_path}")
            else:
                print(f"    ERROR: could not convert generated HTML {source_path}")
            return result

        if ext not in PANDOC_EXTENSIONS:
            print(f"    Skipping: unsupported file type {os.path.basename(source_path)}")
            return None

        if os.path.exists(output_path) and not force:
            print(f"    Skipping: {output_path} already exists")
            return None

        tool = pandoc or find_pandoc()
        if not tool:
            print(f"    Skipping: pandoc not found for {source_path}")
            return None

        if force and os.path.exists(output_path):
            try:
                os.remove(output_path)
            except OSError:
                pass

        text = _pandoc_markdown(source_path, output_path, tool)
        if text is None:
            print(f"    ERROR: pandoc failed to convert {source_path}")
            return None

        _sync_mtime(source_path, output_path)
        print(f"    ✓ Converted: {source_path} -> {output_path}")
        return output_path
    except Exception as e:
        print(f"    ERROR: converting {source_path}: {e}")
        return None


def convert_tree(root: str, pandoc: Optional[str] = None, force: bool = False) -> list:
    """Walk root, convert every convertible file.

    Pages generated by this tool are converted with markdownify when pandoc is
    unavailable; other formats are skipped in that case. Returns list of md
    paths written. Never raises; print one line per conversion/failure (via
    convert_file).
    """
    written = []
    try:
        tool = pandoc or find_pandoc()
        generated_ok = markdownify_available()
        if tool is None and not generated_ok:
            print("    Note: no Markdown converter available "
                  "(install pandoc and/or markdownify); skipping conversion.")
            return written
        if tool is None:
            print("    Note: pandoc not found; converting only HTML pages generated by this tool.")

        for dirpath, dirnames, filenames in os.walk(root):
            dirnames.sort()
            for name in sorted(filenames):
                ext = os.path.splitext(name)[1].lower()
                if ext not in PANDOC_EXTENSIONS:
                    continue
                path = os.path.join(dirpath, name)
                if tool is None and not is_generated_html(path):
                    continue
                result = convert_file(path, pandoc=tool, force=force)
                if result:
                    written.append(result)
    except Exception as e:
        print(f"    ERROR: walking {root}: {e}")
    return written
